name: test
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          cache: true
          cache-dependency-path: go.sum
          go-version: '^1.19.0'
      - name: Lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.48.0
          golangci-lint run ./...
      - name: Vet
        run: go vet ./...
      - name: Unit Tests
        run: |
          go test -v ./... -coverprofile coverage.out -covermode count
          go tool cover -func coverage.out
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.out # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
